version: '3.7'
services:
  jieba:
    image: "limingxinleo/php-jieba:latest"
    build:
      context: "."
    environment:
      APP_ENV: "${APP_ENV:-prod}"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1
networks:
  net:
