on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Build
        run: |
          docker build . -t limingxinleo/php-jieba:latest
          docker tag limingxinleo/php-jieba:latest limingxinleo/php-jieba:${GITHUB_REF_NAME}
          docker login -u limingxinleo -p ${DOCKERHUB_TOKEN}
          docker push limingxinleo/php-jieba:latest
          docker push limingxinleo/php-jieba:${GITHUB_REF_NAME}
