name: PHPUnit for Hyperf

on: [push, pull_request]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }} Swoole ${{ matrix.swoole-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.3', '7.4', '8.0']
        swoole-version: ['4.5.11', '4.6.7']
      max-parallel: 6
      fail-fast: false
    env:
      SW_VERSION: ${{ matrix.swoole-version }}
      JB_VERSION: '1.1.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=1
          coverage: none
          extensions: pdo, pdo_mysql, redis
      - name: Setup Swoole
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/v${SW_VERSION}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Setup Jieba
        run: |
          wget https://github.com/limingxinleo/php-jieba-ext/archive/refs/tags/v${JB_VERSION}.tar.gz -O jieba.tar.gz
          mkdir -p jieba
          tar -xf jieba.tar.gz -C jieba --strip-components=1
          rm jieba.tar.gz
          cd jieba
          g++ -o libjieba.so -fPIC -c -DLOGGING_LEVEL=LL_WARNING -I./include/ lib/jieba.cpp
          phpize
          ./configure
          make
          sudo make install
          sudo sh -c "echo extension=jieba.so > /etc/php/${{ matrix.php-version }}/cli/conf.d/jieba.ini"
      - name: Show Environment
        run: |
          php -v
          php -m
          php -i
      - name: Setup Packages
        run: composer update -o
      - name: Run Test Cases
        run: |
          php bin/hyperf.php start &
          composer analyse
          composer test
